apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-rmq-gp3-ebs
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: gp3
  encrypted: "true"
